#colors
background              = 0xff282828
base                    = 0xff282828
text                    = 0xffebdbb2
alternate_base          = 0xff282828
bright_text             = 0xffebdbb2
accent                  = 0xffebdbb2
accent_secondary        = 0xffebdbb2
#fonts
h1_size                 = 22
h2_size                 = 18
h3_size                 = 15
font_size               = 14
small_font_size         = 12
font_family             = JetBrainsMono Nerd Font
font_family_monospace   = JetBrainsMono Nerd Font
rounding_large          = 8
rounding_small          = 4
icon_theme              = Gruvbox-Plus-Dark