require("config.colors")
require("modules.monitors")
require("modules.env")
require("modules.autostart")
require("modules.core")
require("modules.rules")
require("modules.binds")
require("modules.animations")
require("modules.lang")

