-- Generated by Noctalia

local primary = "rgb(98971a)"
local surface = "rgb(fbf1c7)"
local secondary = "rgb(d79921)"
local error = "rgb(cc241d)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = surface,
		},
	},

	group = {
		col = {
			border_active = secondary,
			border_inactive = surface,
			border_locked_active = error,
			border_locked_inactive = surface,
		},

		groupbar = {
			col = {
				active = secondary,
				inactive = surface,
				locked_active = error,
				locked_inactive = surface,
			},
		},
	},
})
