hl.curve("cubic",          { type = "bezier", points = { {0.2, 1},    {0.5, 1}     } })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "cubic" })
hl.animation({ leaf = "border",        enabled = true,  speed = 3, bezier = "cubic" }) 
hl.animation({ leaf = "windows",       enabled = true,  speed = 4,  bezier = "cubic" }) 
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 3,   bezier = "cubic",         style = "popin 80%" }) 
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1,   bezier = "cubic",       style = "popin 90%" }) 
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 2,   bezier = "cubic" }) 
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1,   bezier = "cubic" }) 
hl.animation({ leaf = "fade",          enabled = true,  speed = 3,   bezier = "cubic" }) 
hl.animation({ leaf = "layers",        enabled = true,  speed = 3, bezier = "cubic", style = "popin 95%" }) 
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 3,    bezier = "cubic", style = "popin 95%" }) 
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 2,  bezier = "cubic",       style = "popin 95%" }) 
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 2, bezier = "cubic" }) 
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 2, bezier = "cubic" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 4, bezier = "cubic", style = "slide" }) 
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 5, bezier = "cubic", style = "slide" })  
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 7, bezier = "cubic", style = "slidefade" }) 
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 4,    bezier = "cubic" })   