[idle]
pre_action_fade_seconds = 2.0
[idle.behavior.lock]
timeout = 600
command = "noctalia:session lock"
enabled = true

[idle.behavior.screen-off]
timeout = 660
command = "noctalia:dpms-off"
resume_command = "noctalia:dpms-on"
enabled = false